name: Deploy to VDS

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            set -e
            echo "Подключение успешно!"

            # Переходим в папку проекта
            cd /var/DutySchedule

            # Разрешаем Git работать с этой папкой (решает ошибку dubious ownership)
            git config --global --add safe.directory /var/DutySchedule

            # Обновляем файлы
            git pull

            # Проверяем, существует ли контейнер
            if docker ps -a --format '{{.Names}}' | grep -q "^DutySchedule$"; then
              echo "Контейнер DutySchedule найден, перезапускаем..."
              docker restart DutySchedule
            else
              echo "Контейнер DutySchedule не найден, создаём и запускаем..."
              docker run -d --name DutySchedule -p 80:80 -v $(pwd):/usr/share/nginx/html:ro nginx:alpine
            fi